# Should ideally create user passwords dynamically like the following but failing:
- name: Rundeck | encode users password
  shell: "java -cp {{ rundeck_jetty_jar }} org.eclipse.jetty.util.security.Password {{ item.name }} {{ item.password }} 2>&1 | grep MD5"
  become: True
  register: rundeck_encoded_users
  when: rundeck_users|length > 0
  with_items: "{{ rundeck_users }}"

- name: Rundeck | users passswords
  debug: var=rundeck_encoded_users
  when: rundeck_users|length > 0

- name: Rundeck | update basic security to have users
  lineinfile:
    dest: /etc/rundeck/realm.properties
    regexp: "^{{ item.item.name }}:{{ item.stdout }},{{ item.item.roles|join(',')}}"
    line: "{{ item.item.name }}:{{ item.stdout }},{{ item.item.roles|join(',')}}"
    state: present
  when: rundeck_users|length > 0 and rundeck_encoded_users|success
  with_items: "{{ rundeck_encoded_users.results }}"
  notify:
    - restart rundeck
  tags:
    - rundeck
    - users

- name: Rundeck | remove admin user
  lineinfile:
    backup: yes
    dest: /etc/rundeck/realm.properties
    regexp: "^admin:admin,user,admin,architect,deploy,build"
    state: absent
  when: rundeck_users|length > 0
  notify:
    - restart rundeck
  tags:
    - rundeck
    - users