---

- name: Install WebUpd8 apt key
  apt_key: id=EEA14886 keyserver='keyserver.ubuntu.com' state=present
  register: webupd8key
  until: webupd8key|success
  retries: 5
  delay: 10

- name: Install WebUpd8 Team Java PPA (for Oracle Java)
  apt_repository: repo='deb http://ppa.launchpad.net/webupd8team/java/ubuntu precise main' state=present mode=0644
  when: java_needs_oracle

- name: Remove WebUpd8 Team Java PPA (for Oracle Java)
  apt_repository: repo='deb http://ppa.launchpad.net/webupd8team/java/ubuntu precise main' state=present mode=0644
  when: java_cleanup and not java_needs_oracle
