---
- name: Install Ansible
  hosts: ansiblecm
  become: true
  roles:
    - geerlingguy.repo-epel
  tasks:
    - name: Install ansible package from EPEL
      package: name=ansible

- name: Install Rundeck
  hosts: ansiblecm
  become: true
  vars:
    rundeck_ansible_keydir: /var/lib/rundeck/var/ansible
    rundeck_ansible_key: "{{ rundeck_ansible_keydir }}/master"
  roles:
    - { role: geerlingguy.java, tags: roles}
    - { role: neel.rundeck,
        rundeck_plugins: [
          'https://github.com/Batix/rundeck-ansible-plugin/releases/download/2.0.2/ansible-plugin-2.0.2.jar'
        ],
        tags: roles
      }
  tasks:
    - name: Copy ansible.cfg file
      template: src=files/ansible.cfg dest=/etc/ansible/ansible.cfg
    - name: Install rundeck-cli
      package: name=rundeck-cli state=present
    - name: Create dir to store ansible key for use with rundeck
      file: state=directory dest='{{ rundeck_ansible_keydir }}' mode=0750 owner=rundeck
    - name: Copy our master SSH private key to the dir
      copy:
        src: ../provision/ssh/master
        dest: "{{ rundeck_ansible_key }}"
        owner: rundeck
        mode: 0600
