---
galaxy_info:
  author: Michaël Rigart
  description: An ansible role for installing RabbitMQ.
  company: Netronix.be
  license: GPLv3
  min_ansible_version: 2.2
  platforms:
    - name: Ubuntu
      versions:
        - all
  categories:
    - networking
dependencies: []

